version: '3.8'

services:
  frontend:
    image: 0x626f6d62612e6361740d0a/frontend:latest
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    image: 0x626f6d62612e6361740d0a/backend:latest
    environment:
      MYSQL_HOST: db
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: 0x626f6d62612e6361740d0a/db:latest
    environment:
      MYSQL_ROOT_PASSWORD: demo
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
