version: '3.8'

services:
  m324_ifz2326:
    image: mysql:8.0
    container_name: m324_ifz2326
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
